import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/NavBar Component/nav'
import Footer from '@/components/Footer comp/Footer'
// import { useRouter } from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav/>
        {children}
        <div className='h-[10vh] w-[10vw]'></div>
        <Footer/>
        </body>
    </html>
  )
}
